sudo: required

services:
  - docker

language: bash

env:
  global:
  - ALPINE_VERSION: v3.8
  matrix:
  - OS: linux
    ARCH: armhf
  - OS: linux
    ARCH: aarch64
  - OS: linux
    ARCH: x86_64
  - OS: linux
    ARCH: i386

stage: Build Docker Images
script:
  - docker run
    --rm
    --privileged
    multiarch/qemu-user-static:register
    --reset
  - docker run
    --rm
    -v /var/run/docker.sock:/var/run/docker.sock
    -v $(pwd):/workdir
    -w /workdir
    --privileged
    -e "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
    -e "TRAVIS_BRANCH=$TRAVIS_BRANCH"
    -e "DOCKER_USER=$DOCKER_USER"
    -e "DOCKER_PASS=$DOCKER_PASS"
    -e "OS=$OS"
    multiarch/alpine:$ARCH-$ALPINE_VERSION
    /bin/sh ./.travis-ci.sh

jobs:
  include:
    - stage: Add Docker Main Image Manifest
      script:
        - docker run
          --rm
          -v $(pwd):/workdir
          -w /workdir
          weshigbee/manifest-tool
          --username "$DOCKER_USER"
          --password "$DOCKER_PASS"
          push from-spec manifest.yml
      env:
        - ARCH: none
          OS: none
