sudo: required

services:
  - docker

language: bash

script: &build
  - ./prepare-qemu.sh
  - ./build-docker-image.sh

jobs:
  include:
    - stage: Build Docker Images
      name: arm32v6 on linux
      script: *build
      env:
        - OS: linux
          ARCH: arm

    - stage: Build Docker Images
      name: arm64v8 on linux
      script: *build
      env:
        - OS: linux
          ARCH: aarch64

    - stage: Build Docker Images
      name: amd64 on linux
      script: *build
      env:
        - OS: linux
          ARCH: x86_64

    - stage: Build Docker Images
      name: i386 on linux
      script: *build
      env:
        - OS: linux
          ARCH: i386

    - stage: Build Docker Images
      name: s390x on linux
      script: *build
      env:
        - OS: linux
          ARCH: s390x

    - stage: Build Docker Images
      name: ppc64le on linux
      script: *build
      env:
        - OS: linux
          ARCH: ppc64le

    - stage: Add Docker Main Image Manifest
      script:
        - ./create-manifest.sh
